#!/bin/sh

VERSION=1.8.0

NGINX_CONF="--prefix=/nginx \
--conf-path=/nginx/conf/nginx.conf \
--sbin-path=/nginx/nginx \
--pid-path=/tmp/nginx.pid \
--lock-path=/tmp/nginx.lock \
--error-log-path=/tmp/error.log \
--http-log-path=/tmp/access.log \
--http-client-body-temp-path=/tmp/client-body \
--http-proxy-temp-path=/tmp/proxy \
--http-fastcgi-temp-path=/tmp/fastcgi \
--http-scgi-temp-path=/tmp/scgi \
--http-uwsgi-temp-path=/tmp/uwsgi \
--with-cc-opt=-fPIC \
--with-ld-opt=-shared \
--without-http_rewrite_module"


mkdir -p dl
wget -P dl http://nginx.org/download/nginx-$VERSION.tar.gz
mkdir -p build
cd build
tar -xz --strip-component 1 -f ../dl//nginx-$VERSION.tar.gz

#Patch extracted NGINX files
for i in ../patches/*; do patch -p1 < $i; done

#Run configuration from  NGINX Source files
. ../preset_args.sh 
(./configure ${NGINX_CONF})

#Build NGINX
make
